baseURL = "https://rebelsec.github.io/"
theme = "NgeBlog"
title = "Rebelsec"
summaryLength = 20

# default amount of posts in each pages
paginate = 6

# Request config about taxonomies
[params]
  request_form_url = "#"
  Description = "Belajar dari dasar dan Bangun kemampuan Seputar Cyber Security, Bug Bounty, Teknologi Informasi, Pemrograman, dan Linux Berbahasa Indonesia mulai dari nol."
  Keywords = "Cyber Security, Bug Bounty, Teknologi Informasi, Pemrograman, Linux "

# Author config
[params.author]
  name = "Galatia Sijabat"
  disclaimer = "Situs ini merupakan informasi tentang saya, tulisan, opini dan kebanyakan adalah dokumentasi untuk saya pribadi ketika sedang belajar atau membagikan sesuatu. Setiap tindakan yang Anda lakukan setelah membaca tulisan di Situs ini merupakan tanggung jawab Anda sendiri. saya tidak bertanggung jawab terhadap kerugian atau kerusakan yang mungkin terjadi."
  email = "galatiasijabat03@gmail.com"
  link = "https://www.rebelsec.id"
  twitter = "@rebelsec"

# Social config about the author
[params.social]
  GitHub = "https://github.com/rebelsec/"
  Linkedin = "https://www.linkedin.com/in/galatiasijabat/"
  Gmail = "mailto:galatiasijabat03@gmail.com"
  Telegram = "https://t.me/rebelsec"
  X = "https://x.com/rebelsec"
  Bugcrowd = ""
  Facebook = ""
  Gitlab = ""
  Hackerone = ""
  Instagram = ""
  Whatsapp = ""
  Medium = ""
  Tumblr = ""
  Quora = ""
  Pinterest = ""
  Reddit = ""
  Codepen = ""
  Bitbucket = ""
  Stackoverflow = ""
  Weibo = ""
  Odnoklassniki = ""
  VK = ""
  Flickr = ""
  Xing = ""
  Snapchat = ""
  Soundcloud = ""
  Spotify = ""
  Hackernews = ""
  Patreon = ""
  Steam = ""
  Twitch = ""
  Strava = ""
  Skype = ""
  Deviantart = ""
  Wordpress = ""
  Googlescholar = ""
  Discord = ""
  HackTheBox = ""

# Menu config
[menu]
  [[menu.main]]
    weight = 1
    identifier = "About"
    name = "About"
    url = "/about/"
    title = "Tentang Saya"
  [[menu.main]]
    weight = 2
    identifier = "Article"
    name = "Article"
    url = "/posts/"
    title = "Semua Postingan"
  [[menu.main]]
    weight = 3
    identifier = "Portfolio"
    name = "Portfolio"
    url = "/portfolio/"
    title = "Portfolio Saya"
  [[menu.main]]
    weight = 4
    identifier = "Contact"
    name = "Contact"
    url = "/contact/"
    title = "Kontak Saya"
[outputs]
  home = ["HTML", "RSS"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]

[mediaTypes]
  [mediaTypes."text/html"]
    suffixes = ["html"]
  [mediaTypes."text/xml"]
    suffixes = ["xml"]
  [mediaTypes."application/rss+xml"]
    suffixes = ["xml"]
